version: '3'

services:
  postgres:
    container_name: crypto-postgres
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - crypto-postgres:/var/lib/postgres/data
    networks:
      - crypto_network
  extraction:
    container_name: crypto-extraction
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - crypto_network
    depends_on:
      - postgres

volumes:
  crypto-postgres:

networks:
  crypto_network: