version: '3'

services:
  postgres:
    container_name: crypto-postgres
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - crypto-data:/var/lib/postgresql/data
    networks:
      - crypto-network
  extraction:
    container_name: crypto-extraction
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - crypto-network
    depends_on:
      - postgres

volumes:
  crypto-data:

networks:
  crypto-network: