version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - crypto_network
  load_data:
    container_name: crypto-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    networks:
      - crypto_network
    depends_on:
      - postgres
  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #     PGADMIN_LISTEN_PORT: 80
  #   ports:
  #     - "5000:80"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - crypto_network

networks:
  crypto_network: